apiVersion: v1
kind: Pod
metadata:
  name: debug
  namespace: roboshop
  labels:
    project: roboshop
    name: debug
spec:
  containers:
  - name: debug
    image: arunt98/debug:v1
    imagePullPolicy: Always
