  
---  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: roboshop
  labels:
    project: roboshop
    component: frontend
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      projcet: roboshop
      component: frontend
      tier: frontend
  template:
    metadata:
      labels:
        project: roboshop
        component: frontend
        tier: frontend
    spec:
      containers:
      - name: frontend
        image: frontend:v1
        imagePullPolicy: Always
        ports:
        - name: liveness-port
          containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: liveness-port
          initialDelaySeconds: 1
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: liveness-port
          initialDelaySeconds: 1
          periodSeconds: 10


---

apiVersion: v1
kind: Service
metadata:
  name: payment
  namespace: roboshop
  labels:
    project: roboshop
    component: frontend
    tier: frontend
spec:
  type: LoadBalancer
  selector:
    project: roboshop
    component: frontend
    tier: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80


        