---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: roboshop
  labels:
    project: roboshop
    component: redis
    tier: backend

spec:
  replicas: 3
  selector:
    matchLabels:
      project: roboshop
      component: redis
      tier: backend

  template:
    metadata:
      labels:
        project: roboshop
        component: redis
        tier: backend 
    spec:
      containers:
      - name: redis
        image: redis:7.0
        imagePullPolicy: Always
        ports:
        - name: liveness-port
          containerPort: 6379
        readinessProbe:
          httpGet:
            path: /health
            port: liveness-port
            periodSeconds: 15
            initialDelaySeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: liveness-port
            periodSeconds: 15
            initialDelaySeconds: 10


---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: roboshop
  labels:
    project: roboshop
    component: redis
    tier: backend
spec:
  selector:
    project: roboshop
    component: redis
    tier: backend
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379







